<?php
/**
 * Copyright (c) 2024–2026 MWBM Partners Ltd (MWservices).
 * All rights reserved.
 *
 * This source code is proprietary and confidential.
 * Unauthorised copying, modification, or distribution is strictly prohibited.
 */

/**
 * ============================================================================
 * 🔗 Go2My.Link — Shortlink Redirect Entry Point (Component B)
 * ============================================================================
 *
 * Entry point for g2my.link — the default short URL redirect domain.
 * Also handles custom org domains (camsda.link, tyney.link, etc.).
 *
 * This is the PERFORMANCE-CRITICAL component. Every short URL redirect
 * passes through this file. Minimal overhead, no template rendering.
 *
 * Flow:
 *   1. Extract short code from ?code= (set by .htaccess) — an EMPTY code (a
 *      root/bare-domain request) first checks the custom-domain LinksPage
 *      fallback (#46) before falling back to redirect.fallback_url
 *   2. Resolve the short code via resolver functions (→ sp_lookupShortURL)
 *   3. Optionally validate destination URL accessibility
 *   4. Log the activity (respecting DNT and analytics setting), optionally
 *      capturing whitelisted tracking params from the request (#92, OFF by
 *      default — analytics.capture_tracking_params) and/or the client IP's
 *      country/region/city (#43, OFF by default — analytics.geolocation_enabled,
 *      and a total no-op unless a GeoIP database is also deployed)
 *   5. Optionally forward the link's own configured UTM params onto the
 *      destination (#92, OFF by default — redirect.forward_utm_params)
 *   6. Issue 302 redirect, OR — for an otherwise-404 'not_found' code on a
 *      verified custom domain with a designated published LinksPage (#46) —
 *      render that LinksPage; otherwise show the branded error page
 *
 * @package    Go2My.Link
 * @subpackage ComponentB
 * @author     MWBM Partners Ltd (MWservices)
 * @version    0.6.0
 * @since      Phase 2 (refactored Phase 3; UTM capture/forward added v1.1.0 /
 *             #92; custom-domain LinksPage fallback added v1.2.0 / #46;
 *             IP geolocation added v1.1.0 / #43)
 * ============================================================================
 */

// ============================================================================
// 📦 Step 1: Load Component Auth Credentials
// ============================================================================

$componentAuthPath = dirname(__DIR__)
    . DIRECTORY_SEPARATOR . '.auth'
    . DIRECTORY_SEPARATOR . 'auth_creds.php';

if (file_exists($componentAuthPath))
{
    require_once $componentAuthPath;
}
else
{
    error_log('[Go2My.Link] CRITICAL: Component B auth_creds.php not found at: ' . $componentAuthPath);
}

// ============================================================================
// 🏷️ Step 2: Define Component Constants
// ============================================================================

define('G2ML_COMPONENT',        'B');
define('G2ML_COMPONENT_NAME',   'Shortlink Redirect');
define('G2ML_COMPONENT_DOMAIN', 'g2my.link');

// Define G2ML_ROOT before page_init.php (web/ directory)
define('G2ML_ROOT', dirname(__DIR__, 2));

// ============================================================================
// 🚀 Step 3: Bootstrap the Application
// ============================================================================

require_once G2ML_ROOT
    . DIRECTORY_SEPARATOR . '_includes'
    . DIRECTORY_SEPARATOR . 'page_init.php';

// ============================================================================
// 🧯 Step 3b: Apache ErrorDocument Dispatch (#114)
// ============================================================================
// Some errors (e.g. a Require-denied 403 on a blocked directory such as
// .auth/, or a PHP fatal 500 with no output) are generated by Apache itself
// and never reach the short-code resolver below — no request runs through
// this file first. The ErrorDocument directives in .htaccess route those
// straight back here via ?http_error=, so G2ML_COMPONENT and page_init.php
// (above) are already in place before the branded pages' Direct Access Guard
// runs. Whitelisted to a fixed set of codes only; anything else (including
// the normal ?code= short-code requests) falls straight through to Step 4
// below completely untouched — this branch adds zero overhead to the
// successful-redirect hot path.
// ============================================================================

$httpErrorCode = $_GET['http_error'] ?? '';

if ($httpErrorCode === '403' || $httpErrorCode === '404' || $httpErrorCode === '500')
{
    if ($httpErrorCode === '403')
    {
        http_response_code(403);

        if (function_exists('__'))
        {
            $errorTitle   = __('error.403_title');
            $errorMessage = __('error.403_message');
        }
        else
        {
            $errorTitle   = '403 — Forbidden';
            $errorMessage = 'You do not have permission to access this resource.';
        }

        require __DIR__ . DIRECTORY_SEPARATOR . '403.php';
    }
    elseif ($httpErrorCode === '500')
    {
        http_response_code(500);

        if (function_exists('__'))
        {
            $errorTitle   = __('error.500_title');
            $errorMessage = __('error.500_message');
        }
        else
        {
            $errorTitle   = '500 — Server Error';
            $errorMessage = 'Something went wrong on our end. Please try again later.';
        }

        require __DIR__ . DIRECTORY_SEPARATOR . '500.php';
    }
    else
    {
        http_response_code(404);

        // Deliberately does NOT set $errorTitle/$errorMessage here — 404.php
        // already supplies its own '404 — Link Not Found' default via `??`
        // (see its "Set Default Values" step below), so leaving both unset
        // reuses that default instead of duplicating the string here.

        require __DIR__ . DIRECTORY_SEPARATOR . '404.php';
    }

    exit;
}

// ============================================================================
// 📦 Step 4: Load Component B Function Files
// ============================================================================

$componentFunctionsDir = dirname(__DIR__) . DIRECTORY_SEPARATOR . '_functions';

require_once $componentFunctionsDir
    . DIRECTORY_SEPARATOR . 'domain_resolver.php';

require_once $componentFunctionsDir
    . DIRECTORY_SEPARATOR . 'redirect_resolver.php';

// ============================================================================
// 🔒 Step 5: Determine Logging Behaviour
// ============================================================================
// Respect the Do Not Track (DNT) header when the analytics.respect_dnt
// setting is enabled. Click counts are still updated (aggregate, not PII).
//
// 📖 Reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/DNT
// ============================================================================

$shouldLog = getSetting('analytics.log_activity', true);
$respectDNT = getSetting('analytics.respect_dnt', true);
$isDNT = (isset($_SERVER['HTTP_DNT']) && $_SERVER['HTTP_DNT'] === '1');

if ($respectDNT && $isDNT)
{
    $shouldLog = false;
}

// ============================================================================
// 🌐 Step 6: Determine Requesting Domain
// ============================================================================
// Custom org domains (camsda.link, tyney.link, etc.) are resolved to their
// org handle by the sp_lookupShortURL stored procedure.
//
// Moved AHEAD of short-code extraction (below) so the empty-short-code /
// root-request branch can consult the custom-domain LinksPage fallback
// (#46) — which needs to know the Host — BEFORE falling back to the generic
// redirect.fallback_url setting. This reordering does not touch the
// successful-redirect path at all: $requestDomain was always computed
// unconditionally on every request either way.
// ============================================================================

$requestDomain = $_SERVER['HTTP_HOST'] ?? 'g2my.link';

// Strip port number if present (e.g., localhost:8080)
// 📖 Reference: https://www.php.net/manual/en/function.strpos.php
if (strpos($requestDomain, ':') !== false)
{
    $requestDomain = explode(':', $requestDomain)[0];
}

// ============================================================================
// 🔀 Step 7: Extract Short Code
// ============================================================================

$shortCode = trim($_GET['code'] ?? '');

// No short code provided (a root / bare-domain request).
if ($shortCode === '')
{
    // ------------------------------------------------------------------------
    // 📄 Custom-domain LinksPage fallback (#46) — ONLY reached on this
    // already-off-the-hot-path branch ($shortCode === ''). A normal
    // short-code redirect never enters this if-block at all, so this adds
    // ZERO overhead to the successful-redirect path (Step 9 below).
    //
    // g2ml_renderCustomDomainLinksPageFallback() independently re-checks the
    // domain is verified+active (#91) and the designated page is still
    // published+active (#46) — it returns false instantly, with nothing
    // echoed, unless every condition is met, so falling through to the
    // EXISTING fallback-URL redirect immediately below is always safe.
    // 📖 Reference: web/G2My.Link/_functions/linkspage_fallback.php
    // ------------------------------------------------------------------------
    require_once $componentFunctionsDir . DIRECTORY_SEPARATOR . 'linkspage_fallback.php';

    if (g2ml_renderCustomDomainLinksPageFallback($requestDomain))
    {
        if ($shouldLog)
        {
            logActivity('redirect', 'linkspage_fallback', 200, [
                'logData' => ['reason' => 'Custom-domain LinksPage fallback (root request)', 'requestDomain' => $requestDomain],
            ]);
        }

        exit;
    }

    $fallbackURL = getSetting('redirect.fallback_url', 'https://go2my.link');

    if ($shouldLog)
    {
        logActivity('redirect', 'no_code', 302, [
            'logData' => ['reason' => 'Empty short code'],
        ]);
    }

    buildRedirectResponse($fallbackURL, 302);
    // buildRedirectResponse calls exit — execution stops here
}

// ============================================================================
// 📞 Step 8: Resolve the Short Code
// ============================================================================
// The resolveShortCode() function wraps sp_lookupShortURL which handles:
//   - Domain-to-org mapping
//   - Alias chain resolution (max 3 hops)
//   - Date range validation (startDate / endDate)
//   - Active status check (isActive flag)
//   - Fallback URL provision
//
// 📖 Reference: web/G2My.Link/_functions/redirect_resolver.php
// 📖 Reference: web/_sql/procedures/sp_lookupShortURL.sql
// ============================================================================

$result = resolveShortCode($requestDomain, $shortCode);

$destination = $result['destination'];
$status      = $result['status'];
$orgHandle   = $result['orgHandle'];

// ============================================================================
// ❌ Handle SP Error (database failure)
// ============================================================================

if ($status === 'error')
{
    if ($shouldLog)
    {
        logActivity('redirect', 'error', 500, [
            'shortCode' => $shortCode,
            'logData'   => ['reason' => 'SP call failed'],
        ]);
    }

    http_response_code(500);
    $errorTitle   = 'Service Temporarily Unavailable';
    $errorMessage = 'Please try again in a few moments.';
    require __DIR__ . DIRECTORY_SEPARATOR . '404.php';
    exit;
}

// ============================================================================
// ✅ Step 9: Handle Successful Resolution
// ============================================================================

if ($status === 'success' && $destination !== null && $destination !== '')
{
    // 🔍 Optional: Validate destination URL accessibility
    // Gated behind setting — OFF by default for performance
    // 📖 Reference: web/G2My.Link/_functions/redirect_resolver.php — validateDestination()
    $shouldValidate = getSetting('redirect.validate_destination', false);

    if ($shouldValidate)
    {
        $validation = validateDestination($destination);

        if (!$validation['valid'])
        {
            if ($shouldLog)
            {
                logActivity('redirect', 'validation_failed', 503, [
                    'orgHandle'      => $orgHandle,
                    'shortCode'      => $shortCode,
                    'destinationURL' => $destination,
                    'logData'        => [
                        'validationError' => $validation['error'],
                        'statusCode'      => $validation['statusCode'],
                    ],
                ]);
            }

            // Show the validation page with countdown to fallback
            require __DIR__ . DIRECTORY_SEPARATOR . 'validating.php';
            exit;
        }
    }

    // 📊 Log the successful redirect
    $redirectCode = (int) getSetting('redirect.default_code', 302);

    if ($shouldLog)
    {
        // ====================================================================
        // 🔗 CueRCode scan attribution (#145) — only computed when we are
        // actually going to log (never wastes a DB round trip when DNT/GPC or
        // the analytics.log_activity switch has logging off).
        //
        // qrCodeExternalID is NEVER taken from the query string — it is
        // looked up from the STORED short URL row for the code that was
        // actually requested (scoped to the resolved org), so a visitor can
        // never forge attribution to an arbitrary QR id by guessing a
        // qrCodeExternalID in the URL. This adds one indexed lookup
        // (UQ_shortcode_org) ONLY on the scan-tagged path — a normal redirect
        // (no matching scan-source param) never reaches it.
        //
        // 📖 Reference: web/G2My.Link/_functions/redirect_resolver.php — g2ml_resolveScanSource()
        // ====================================================================
        $scanSource = g2ml_resolveScanSource(
            (string) getSetting('cuercode.scan_source_param', 'src'),
            (string) getSetting('cuercode.scan_source_value', 'qr'),
            $_GET
        );

        $qrCodeExternalIDForLog = null;

        if ($scanSource !== null)
        {
            $qrLinkRow = dbSelectOne(
                "SELECT qrCodeExternalID FROM tblShortURLs WHERE shortCode = ? AND orgHandle = ? LIMIT 1",
                'ss',
                [$shortCode, $orgHandle]
            );

            if ($qrLinkRow !== null && $qrLinkRow !== false && $qrLinkRow['qrCodeExternalID'] !== null)
            {
                $qrCodeExternalIDForLog = (int) $qrLinkRow['qrCodeExternalID'];
            }
        }

        // ====================================================================
        // 📥 Tracking-param capture (#92) — OFF by default
        // (analytics.capture_tracking_params). Only computed when we are
        // actually going to log, exactly like scanSource above. Extraction is
        // a pure in-memory whitelist check ($_GET only) — no additional
        // database round trip either way, so this adds negligible CPU and
        // ZERO extra queries to the hot path even when the setting is on.
        // When the setting is off (default), this block is skipped entirely
        // and $logDataForRedirect stays null, so the INSERT below is
        // byte-for-byte identical to before this feature existed.
        //
        // 📖 Reference: web/G2My.Link/_functions/redirect_resolver.php — g2ml_extractTrackingParams()
        // ====================================================================
        $logDataForRedirect = null;

        $shouldCaptureTrackingParams = getSetting('analytics.capture_tracking_params', false);

        if ($shouldCaptureTrackingParams)
        {
            $capturedTrackingParams = g2ml_extractTrackingParams($_GET);

            if (count($capturedTrackingParams) > 0)
            {
                $logDataForRedirect = ['trackingParams' => $capturedTrackingParams];
            }
        }

        // ====================================================================
        // 🌍 IP geolocation (#43) — OFF by default (analytics.geolocation_enabled)
        // AND a total no-op unless the configured .mmdb database file is also
        // present — g2ml_geolocationAvailable() (web/_functions/geolocation.php)
        // is the ONLY check made here: one cached getSetting() boolean plus one
        // is_file()/is_readable() call. Computed here, only inside the
        // $shouldLog branch, exactly like scanSource/logData above — a request
        // that is not going to be logged at all (DNT/GPC, or
        // analytics.log_activity off) never triggers a geolocation lookup
        // either, so this adds NO new tracking surface beyond what was already
        // being logged. When the setting is off or the database is absent,
        // these three values stay null and the INSERT below is byte-for-byte
        // identical to before this feature existed.
        //
        // 📖 Reference: web/_functions/geolocation.php — g2ml_geolocateIP()
        // ====================================================================
        $geoCountryCode = null;
        $geoRegionCode  = null;
        $geoCityName    = null;

        if (function_exists('g2ml_geolocationAvailable') && g2ml_geolocationAvailable())
        {
            $geoResult      = g2ml_geolocateIP(g2ml_getClientIP());
            $geoCountryCode = $geoResult['countryCode'];
            $geoRegionCode  = $geoResult['regionCode'];
            $geoCityName    = $geoResult['cityName'];
        }

        logActivity('redirect', 'success', $redirectCode, [
            'orgHandle'        => $orgHandle,
            'shortCode'        => $shortCode,
            'destinationURL'   => $destination,
            'scanSource'       => $scanSource,
            'qrCodeExternalID' => $qrCodeExternalIDForLog,
            'logData'          => $logDataForRedirect,
            'countryCode'      => $geoCountryCode,
            'regionCode'       => $geoRegionCode,
            'cityName'         => $geoCityName,
        ]);
    }

    // 📈 Update click count and last click timestamp (fire-and-forget)
    // This is aggregate data (not PII) so it runs even when DNT is set
    dbUpdate(
        "UPDATE tblShortURLs
         SET clickCount = clickCount + 1,
             lastClickAt = NOW()
         WHERE shortCode = ?
           AND orgHandle = ?",
        'ss',
        [$shortCode, $orgHandle]
    );

    // ========================================================================
    // 🔗 UTM forwarding (#92) — OFF by default (redirect.forward_utm_params).
    // Computed here, just before emitting the Location header, so the
    // destination logged above and validated earlier (if
    // redirect.validate_destination is on) is always the RAW stored
    // destination — only the actual outbound redirect target is decorated.
    // When the setting is off (default), or the link has no configured UTM
    // values at all, $destinationForRedirect is set to $destination
    // unchanged, so the emitted Location header is byte-for-byte identical
    // to before this feature existed.
    //
    // 📖 Reference: web/G2My.Link/_functions/redirect_resolver.php — g2ml_appendUtmToDestination()
    // ========================================================================
    $destinationForRedirect = $destination;

    $shouldForwardUtm = getSetting('redirect.forward_utm_params', false);

    if ($shouldForwardUtm)
    {
        $linkUtm = [
            'utmSource'   => $result['utmSource'],
            'utmMedium'   => $result['utmMedium'],
            'utmCampaign' => $result['utmCampaign'],
            'utmTerm'     => $result['utmTerm'],
            'utmContent'  => $result['utmContent'],
        ];

        $linkHasAnyUtmValue = false;

        foreach ($linkUtm as $linkUtmValue)
        {
            if ($linkUtmValue !== null && $linkUtmValue !== '')
            {
                $linkHasAnyUtmValue = true;
                break;
            }
        }

        if ($linkHasAnyUtmValue)
        {
            $destinationForRedirect = g2ml_appendUtmToDestination($destination, $linkUtm);
        }
    }

    // 🚀 Issue the redirect
    buildRedirectResponse($destinationForRedirect, $redirectCode);
    // buildRedirectResponse calls exit — execution stops here
}

// ============================================================================
// ❌ Step 10: Handle Error States
// ============================================================================

// Determine HTTP status code and error messaging
switch ($status)
{
    case 'not_found':
        http_response_code(404);
        $errorTitle   = '404 — Link Not Found';
        $errorMessage = 'The short link you requested does not exist or has been removed.';
        break;

    case 'inactive':
        http_response_code(410);
        $errorTitle   = 'Link Disabled';
        $errorMessage = 'This short link has been disabled by its owner.';
        break;

    case 'not_yet_active':
        http_response_code(404);
        $errorTitle   = 'Link Not Yet Active';
        $errorMessage = 'This short link is not yet active. Please try again later.';
        break;

    case 'expired':
        http_response_code(410);
        $errorTitle   = 'Link Expired';
        $errorMessage = 'This short link has expired and is no longer available.';
        break;

    case 'max_hops_exceeded':
        http_response_code(500);
        $errorTitle   = 'Redirect Error';
        $errorMessage = 'This link could not be resolved due to a configuration issue.';
        break;

    case 'no_destination':
        http_response_code(404);
        $errorTitle   = 'Link Not Configured';
        $errorMessage = 'This short link has no destination URL configured.';
        break;

    case 'domain_not_configured':
        // 🔒 #91 — a custom short domain that has NOT passed DNS-TXT ownership
        // verification (or has since failed re-verification). orgHandle is
        // always null for this status — sp_lookupShortURL deliberately never
        // fell back to '[default]' here, so this branded message is the only
        // response a caller of this Host can ever see; no short-code lookup
        // in any org's namespace happened at all.
        http_response_code(404);
        $errorTitle   = 'Domain Not Configured';
        $errorMessage = 'This domain is not yet verified for use with Go2My.Link. If you are the domain owner, finish DNS verification from your dashboard.';
        break;

    default:
        http_response_code(404);
        $errorTitle   = 'Link Not Found';
        $errorMessage = 'The requested link could not be found.';
        break;
}

// Log the error
if ($shouldLog)
{
    $httpCode = http_response_code();
    logActivity('redirect', $status, $httpCode, [
        'orgHandle' => $orgHandle,
        'shortCode' => $shortCode,
        'logData'   => ['spStatus' => $status],
    ]);
}

// If the SP returned a fallback destination, redirect to it
if ($destination !== null && $destination !== '')
{
    buildRedirectResponse($destination, 302);
    // buildRedirectResponse calls exit
}

// ============================================================================
// 📄 Custom-domain LinksPage fallback (#46) — "path does not resolve to a
// short code" branch. Scoped STRICTLY to status === 'not_found' (the short
// code genuinely does not exist in this org's namespace) — every OTHER
// error status (inactive, expired, not_yet_active, no_destination,
// max_hops_exceeded, domain_not_configured) keeps its EXISTING, distinct
// behaviour completely untouched. domain_not_configured in particular can
// never reach this: g2ml_renderCustomDomainLinksPageFallback() performs its
// OWN independent verified+active check against tblOrgShortDomains, so an
// unverified domain claim can never surface a LinksPage this way either.
//
// 🔒 HOT-PATH RULE: this is already inside the error-handling branch — the
// successful-redirect path (Step 9 above) returns/exits long before this
// code is ever reached, so it adds no overhead there.
// 📖 Reference: web/G2My.Link/_functions/linkspage_fallback.php
// ============================================================================
if ($status === 'not_found')
{
    require_once $componentFunctionsDir . DIRECTORY_SEPARATOR . 'linkspage_fallback.php';

    if (g2ml_renderCustomDomainLinksPageFallback($requestDomain))
    {
        exit;
    }
}

// Show the appropriate branded error page
// Variables $errorTitle, $errorMessage, $orgHandle, $status are available
// to the included error page templates
switch ($status)
{
    case 'expired':
    case 'not_yet_active':
        require __DIR__ . DIRECTORY_SEPARATOR . 'expired.php';
        break;

    default:
        require __DIR__ . DIRECTORY_SEPARATOR . '404.php';
        break;
}
exit;
