-- Copyright (c) 2024–2026 MWBM Partners Ltd (MWservices).
-- All rights reserved.
--
-- This source code is proprietary and confidential.
-- Unauthorised copying, modification, or distribution is strictly prohibited.

-- =============================================================================
-- 🧩 Go2My.Link — Seed 023: LinksPage feature registry and plan values (LP-01, #216)
-- =============================================================================
-- WHAT THIS DOES. Registers every feature the LinksPage programme needs in the
-- feature registry (tblFeatures) — including features that are not built
-- yet — and gives each of the four shipped plans (free / basic / premium /
-- enterprise) an explicit value for each one in tblTierFeatures. It also
-- gives plan values to three LinksPage features that seed 018 registered but
-- never gave values to, so the registry describes today's product truthfully.
--
-- WHY. Before this, the only way to put a new feature on some plans and not
-- others was to add a new has* or max* column to tblSubscriptionTiers for
-- every feature. The registry exists to avoid exactly that. With these rows in
-- place, the code asks web/_functions/entitlements.php's
-- g2ml_featureAllowed() / g2ml_featureLimit() by feature name, and the owner
-- moves a feature between plans by changing ONE row, with no code change:
--
--   UPDATE tblTierFeatures
--      SET valueBoolean = 1
--    WHERE tierID = 'free'
--      AND featureUID = (SELECT featureUID FROM tblFeatures
--                         WHERE featureSlug = 'linkspage.hide_branding');
--
-- Those two functions read these rows the same way whether the pricing
-- engine's master switch (billing.pricing_engine_enabled, seed 019) is off or
-- on. This file does NOT switch the engine on and does not change any setting.
--
-- THE VALUES ARE A PROPOSAL (issue #216) FOR THE OWNER TO CONFIRM:
--
--   Feature (registry name)               Free  Basic  Premium  Enterprise
--   linkspage.hide_branding               no    yes    yes      yes
--   linkspage.seo                         no    yes    yes      yes
--   linkspage.click_tracking              yes   yes    yes      yes
--   linkspage.analytics_retention_days    30    90     365      unlimited
--   linkspage.scheduled_links             no    yes    yes      yes
--   linkspage.password_protect            no    no     yes      yes
--   linkspage.image_upload                no    yes    yes      yes
--   linkspage.verified_badge              no    no     yes      yes
--   linkspage.lead_capture                no    no     yes      yes
--   linkspage.tracking_pixels             no    no     yes      yes
--   linkspage.embeds                      no    no     yes      yes
--   linkspage.all_templates (seed 018)    yes   yes    yes      yes
--   linkspage.agegate (seed 018)          yes   yes    yes      yes
--   linkspage.custom_domain (seed 018)    no    yes    yes      yes
--
-- RULES FOR PEOPLE BUILDING LINKSPAGE FEATURES. Do not edit this file (or
-- migration 021) to add or rename a feature: ask the programme lead first,
-- because a renamed feature silently denies everyone (the gate fails closed on
-- an unknown name). Do not add has* / max* columns for LinksPage features.
--
-- WHAT THIS FILE CANNOT DO. It never overwrites a value an operator has
-- changed (re-running is a no-op for existing rows), so it cannot be used to
-- "reset" a plan back to these proposed values — do that with an UPDATE. It
-- only writes rows for the four shipped plans; any other plan falls back to
-- each feature's safe-floor default (off / 30 days).
--
-- ORDER. Needs web/_sql/schema/036_pricing_engine.sql (the tables),
-- web/_sql/seeds/001_subscription_tiers.sql (the plans) and
-- web/_sql/seeds/018_pricing_feature_registry.sql (the three older LinksPage
-- rows in section 3). All three sort earlier, so a fresh install runs them
-- first. ⚠️ Issue #183 (fixed 2026-09-21): schema 036 used to fail to create
-- tblTierFeatures at all on MariaDB, which would have left section 1 below
-- succeeding and every tblTierFeatures row here failing. See the comment
-- above effectiveFromKey in web/_sql/schema/036_pricing_engine.sql for the
-- fix, and migration 021's header for what the fault meant for a MariaDB
-- database installed before the #183 fix.
--
-- SAFE TO RE-RUN. tblFeatures rows refresh their description only;
-- tblTierFeatures rows use an ON DUPLICATE KEY no-op. The SAME statements are
-- reused, unchanged, by web/_sql/migrations/021_linkspage_feature_registry.sql
-- for databases that were installed before this file existed.
--
-- @package    Go2My.Link
-- @subpackage Seeds
-- @author     MWBM Partners Ltd (MWservices)
-- @version    1.0.0
-- @since      2026-09-21 — LinksPage programme, LP-01 (#216)
--
-- 📖 References:
--     - Tables:            web/_sql/schema/036_pricing_engine.sql
--     - Older registry:    web/_sql/seeds/018_pricing_feature_registry.sql
--     - Engine switch:     web/_sql/seeds/019_pricing_settings.sql
--     - The gate:          web/_functions/entitlements.php (g2ml_featureAllowed / g2ml_featureLimit)
--     - The merge rules:   web/_functions/pricing.php (g2ml_pricingResolveOrgTier)
--     - Live databases:    web/_sql/migrations/021_linkspage_feature_registry.sql
-- =============================================================================

USE `mwtools_Go2MyLink`;

-- -----------------------------------------------------------------------------
-- 1. Registry rows — one per LinksPage feature, including the ones that are
--    registered now but not built yet (so their plan values can be agreed and
--    stored before the code exists).
--
--    Every default below is the SAFE FLOOR: "off" for yes/no features, and the
--    Free plan's 30 days for the statistics window. The default is what a plan
--    gets if it has NO tblTierFeatures row, so a plan added later can never be
--    handed a paid extra by accident. linkspage.click_tracking is "on" for
--    every shipped plan (section 2) but its default is still "off", for that
--    same reason.
--
--    A re-run only refreshes the description. It never changes a name, a
--    type, a default or isActive that an operator may have edited.
-- -----------------------------------------------------------------------------
INSERT INTO `tblFeatures` (
    `featureSlug`, `featureName`, `featureDescription`,
    `valueType`, `valueUnit`, `quotaPeriod`,
    `defaultValueBoolean`, `defaultValueInt`, `defaultIsUnlimited`,
    `category`, `isMeterable`, `legacyColumn`, `sortOrder`, `isActive`
) VALUES
('linkspage.hide_branding', 'Hide Lnks.page branding',
 'Leaves the "Powered by Lnks.page" line off the public LinksPage (LP-03).',
 'boolean', NULL, NULL, 0, NULL, 0, 'linkspage', 0, NULL, 60, 1),
('linkspage.seo', 'LinksPage search and sharing controls',
 'Custom page title, description and share image for search engines and social previews, and the option to ask search engines not to list the page (LP-04).',
 'boolean', NULL, NULL, 0, NULL, 0, 'linkspage', 0, NULL, 70, 1),
('linkspage.click_tracking', 'LinksPage click tracking',
 'Counts clicks on each link on a LinksPage (LP-05). The default is off as a safe floor; every shipped plan has an explicit row turning it on.',
 'boolean', NULL, NULL, 0, NULL, 0, 'linkspage', 0, NULL, 80, 1),
('linkspage.analytics_retention_days', 'LinksPage statistics history',
 'How many days of LinksPage click statistics the organisation can see. Unlimited means all of it (LP-06).',
 'limit', 'days', NULL, NULL, 30, 0, 'linkspage', 0, NULL, 90, 1),
('linkspage.scheduled_links', 'LinksPage scheduled links',
 'Show or hide a link on a LinksPage between chosen dates and times (LP-07). Only setting a schedule is gated; a schedule already saved is always honoured.',
 'boolean', NULL, NULL, 0, NULL, 0, 'linkspage', 0, NULL, 100, 1),
('linkspage.password_protect', 'Password-protected LinksPage',
 'Visitors must enter a password before they can see the page (LP-13). Registered now; not built yet.',
 'boolean', NULL, NULL, 0, NULL, 0, 'linkspage', 0, NULL, 110, 1),
('linkspage.image_upload', 'LinksPage image upload',
 'Upload the avatar and link icon images instead of pointing at an image elsewhere on the web (LP-16). Registered now; not built yet.',
 'boolean', NULL, NULL, 0, NULL, 0, 'linkspage', 0, NULL, 120, 1),
('linkspage.verified_badge', 'LinksPage verified badge',
 'A badge showing the page owner has been verified (LP-17). Registered now; not built yet.',
 'boolean', NULL, NULL, 0, NULL, 0, 'linkspage', 0, NULL, 130, 1),
('linkspage.lead_capture', 'LinksPage contact capture form',
 'A form on the page that collects visitor email addresses or contact details (LP-18). Registered now; not built yet; needs legal sign-off first.',
 'boolean', NULL, NULL, 0, NULL, 0, 'linkspage', 0, NULL, 140, 1),
('linkspage.tracking_pixels', 'LinksPage tracking pixels',
 'Third-party analytics and advertising pixels on the page (LP-19). Registered now; not built yet; needs legal sign-off first.',
 'boolean', NULL, NULL, 0, NULL, 0, 'linkspage', 0, NULL, 150, 1),
('linkspage.embeds', 'LinksPage rich embeds',
 'Embedded players such as YouTube and Spotify on the page (LP-20). Registered now; not built yet.',
 'boolean', NULL, NULL, 0, NULL, 0, 'linkspage', 0, NULL, 160, 1)
ON DUPLICATE KEY UPDATE
    `featureDescription` = VALUES(`featureDescription`);

-- -----------------------------------------------------------------------------
-- 2. Per-plan rows — the values the four shipped plans actually get.
--
--    THESE ARE THE PROPOSED VALUES FROM ISSUE #216, FOR THE OWNER TO CONFIRM.
--    Changing one later is a single UPDATE on tblTierFeatures; no code change.
--
--    One INSERT … SELECT per feature, written out plan by plan so each value
--    can be read at a glance. Only the four shipped plans are touched (the
--    WHERE clause), so a throwaway or custom plan never gets rows it did not
--    ask for — it falls back to the safe-floor default from section 1.
--
--    Idempotent via the UQ_tierfeature unique key (tierID, featureUID,
--    undated effectiveFrom) + an ON DUPLICATE KEY no-op: a re-run inserts
--    nothing and NEVER overwrites a value an operator has since changed. A
--    plan or feature that does not exist is simply skipped by the JOIN.
-- -----------------------------------------------------------------------------

-- linkspage.hide_branding: Free no · Basic yes · Premium yes · Enterprise yes
INSERT INTO `tblTierFeatures` (`tierID`, `featureUID`, `valueBoolean`)
SELECT t.`tierID`, f.`featureUID`,
       CASE t.`tierID`
           WHEN 'free'       THEN 0
           WHEN 'basic'      THEN 1
           WHEN 'premium'    THEN 1
           WHEN 'enterprise' THEN 1
       END
FROM   `tblSubscriptionTiers` t
JOIN   `tblFeatures` f ON f.`featureSlug` = 'linkspage.hide_branding'
WHERE  t.`tierID` IN ('free', 'basic', 'premium', 'enterprise')
ON DUPLICATE KEY UPDATE `tierFeatureUID` = `tblTierFeatures`.`tierFeatureUID`;

-- linkspage.seo: Free no · Basic yes · Premium yes · Enterprise yes
INSERT INTO `tblTierFeatures` (`tierID`, `featureUID`, `valueBoolean`)
SELECT t.`tierID`, f.`featureUID`,
       CASE t.`tierID`
           WHEN 'free'       THEN 0
           WHEN 'basic'      THEN 1
           WHEN 'premium'    THEN 1
           WHEN 'enterprise' THEN 1
       END
FROM   `tblSubscriptionTiers` t
JOIN   `tblFeatures` f ON f.`featureSlug` = 'linkspage.seo'
WHERE  t.`tierID` IN ('free', 'basic', 'premium', 'enterprise')
ON DUPLICATE KEY UPDATE `tierFeatureUID` = `tblTierFeatures`.`tierFeatureUID`;

-- linkspage.click_tracking: Free yes · Basic yes · Premium yes · Enterprise yes
INSERT INTO `tblTierFeatures` (`tierID`, `featureUID`, `valueBoolean`)
SELECT t.`tierID`, f.`featureUID`,
       CASE t.`tierID`
           WHEN 'free'       THEN 1
           WHEN 'basic'      THEN 1
           WHEN 'premium'    THEN 1
           WHEN 'enterprise' THEN 1
       END
FROM   `tblSubscriptionTiers` t
JOIN   `tblFeatures` f ON f.`featureSlug` = 'linkspage.click_tracking'
WHERE  t.`tierID` IN ('free', 'basic', 'premium', 'enterprise')
ON DUPLICATE KEY UPDATE `tierFeatureUID` = `tblTierFeatures`.`tierFeatureUID`;

-- linkspage.analytics_retention_days: Free 30 · Basic 90 · Premium 365 ·
-- Enterprise unlimited. Unlimited is stored as isUnlimited = 1 with valueInt
-- NULL — the same convention seed 018 uses for the legacy NULL-means-unlimited
-- limits — and g2ml_featureLimit() reports it as 'limit' => null.
INSERT INTO `tblTierFeatures` (`tierID`, `featureUID`, `valueInt`, `isUnlimited`)
SELECT t.`tierID`, f.`featureUID`,
       CASE t.`tierID`
           WHEN 'free'       THEN 30
           WHEN 'basic'      THEN 90
           WHEN 'premium'    THEN 365
           WHEN 'enterprise' THEN NULL
       END,
       CASE t.`tierID`
           WHEN 'enterprise' THEN 1
           ELSE 0
       END
FROM   `tblSubscriptionTiers` t
JOIN   `tblFeatures` f ON f.`featureSlug` = 'linkspage.analytics_retention_days'
WHERE  t.`tierID` IN ('free', 'basic', 'premium', 'enterprise')
ON DUPLICATE KEY UPDATE `tierFeatureUID` = `tblTierFeatures`.`tierFeatureUID`;

-- linkspage.scheduled_links: Free no · Basic yes · Premium yes · Enterprise yes
INSERT INTO `tblTierFeatures` (`tierID`, `featureUID`, `valueBoolean`)
SELECT t.`tierID`, f.`featureUID`,
       CASE t.`tierID`
           WHEN 'free'       THEN 0
           WHEN 'basic'      THEN 1
           WHEN 'premium'    THEN 1
           WHEN 'enterprise' THEN 1
       END
FROM   `tblSubscriptionTiers` t
JOIN   `tblFeatures` f ON f.`featureSlug` = 'linkspage.scheduled_links'
WHERE  t.`tierID` IN ('free', 'basic', 'premium', 'enterprise')
ON DUPLICATE KEY UPDATE `tierFeatureUID` = `tblTierFeatures`.`tierFeatureUID`;

-- linkspage.password_protect: Free no · Basic no · Premium yes · Enterprise yes
INSERT INTO `tblTierFeatures` (`tierID`, `featureUID`, `valueBoolean`)
SELECT t.`tierID`, f.`featureUID`,
       CASE t.`tierID`
           WHEN 'free'       THEN 0
           WHEN 'basic'      THEN 0
           WHEN 'premium'    THEN 1
           WHEN 'enterprise' THEN 1
       END
FROM   `tblSubscriptionTiers` t
JOIN   `tblFeatures` f ON f.`featureSlug` = 'linkspage.password_protect'
WHERE  t.`tierID` IN ('free', 'basic', 'premium', 'enterprise')
ON DUPLICATE KEY UPDATE `tierFeatureUID` = `tblTierFeatures`.`tierFeatureUID`;

-- linkspage.image_upload: Free no · Basic yes · Premium yes · Enterprise yes
INSERT INTO `tblTierFeatures` (`tierID`, `featureUID`, `valueBoolean`)
SELECT t.`tierID`, f.`featureUID`,
       CASE t.`tierID`
           WHEN 'free'       THEN 0
           WHEN 'basic'      THEN 1
           WHEN 'premium'    THEN 1
           WHEN 'enterprise' THEN 1
       END
FROM   `tblSubscriptionTiers` t
JOIN   `tblFeatures` f ON f.`featureSlug` = 'linkspage.image_upload'
WHERE  t.`tierID` IN ('free', 'basic', 'premium', 'enterprise')
ON DUPLICATE KEY UPDATE `tierFeatureUID` = `tblTierFeatures`.`tierFeatureUID`;

-- linkspage.verified_badge: Free no · Basic no · Premium yes · Enterprise yes
INSERT INTO `tblTierFeatures` (`tierID`, `featureUID`, `valueBoolean`)
SELECT t.`tierID`, f.`featureUID`,
       CASE t.`tierID`
           WHEN 'free'       THEN 0
           WHEN 'basic'      THEN 0
           WHEN 'premium'    THEN 1
           WHEN 'enterprise' THEN 1
       END
FROM   `tblSubscriptionTiers` t
JOIN   `tblFeatures` f ON f.`featureSlug` = 'linkspage.verified_badge'
WHERE  t.`tierID` IN ('free', 'basic', 'premium', 'enterprise')
ON DUPLICATE KEY UPDATE `tierFeatureUID` = `tblTierFeatures`.`tierFeatureUID`;

-- linkspage.lead_capture: Free no · Basic no · Premium yes · Enterprise yes
INSERT INTO `tblTierFeatures` (`tierID`, `featureUID`, `valueBoolean`)
SELECT t.`tierID`, f.`featureUID`,
       CASE t.`tierID`
           WHEN 'free'       THEN 0
           WHEN 'basic'      THEN 0
           WHEN 'premium'    THEN 1
           WHEN 'enterprise' THEN 1
       END
FROM   `tblSubscriptionTiers` t
JOIN   `tblFeatures` f ON f.`featureSlug` = 'linkspage.lead_capture'
WHERE  t.`tierID` IN ('free', 'basic', 'premium', 'enterprise')
ON DUPLICATE KEY UPDATE `tierFeatureUID` = `tblTierFeatures`.`tierFeatureUID`;

-- linkspage.tracking_pixels: Free no · Basic no · Premium yes · Enterprise yes
INSERT INTO `tblTierFeatures` (`tierID`, `featureUID`, `valueBoolean`)
SELECT t.`tierID`, f.`featureUID`,
       CASE t.`tierID`
           WHEN 'free'       THEN 0
           WHEN 'basic'      THEN 0
           WHEN 'premium'    THEN 1
           WHEN 'enterprise' THEN 1
       END
FROM   `tblSubscriptionTiers` t
JOIN   `tblFeatures` f ON f.`featureSlug` = 'linkspage.tracking_pixels'
WHERE  t.`tierID` IN ('free', 'basic', 'premium', 'enterprise')
ON DUPLICATE KEY UPDATE `tierFeatureUID` = `tblTierFeatures`.`tierFeatureUID`;

-- linkspage.embeds: Free no · Basic no · Premium yes · Enterprise yes
INSERT INTO `tblTierFeatures` (`tierID`, `featureUID`, `valueBoolean`)
SELECT t.`tierID`, f.`featureUID`,
       CASE t.`tierID`
           WHEN 'free'       THEN 0
           WHEN 'basic'      THEN 0
           WHEN 'premium'    THEN 1
           WHEN 'enterprise' THEN 1
       END
FROM   `tblSubscriptionTiers` t
JOIN   `tblFeatures` f ON f.`featureSlug` = 'linkspage.embeds'
WHERE  t.`tierID` IN ('free', 'basic', 'premium', 'enterprise')
ON DUPLICATE KEY UPDATE `tierFeatureUID` = `tblTierFeatures`.`tierFeatureUID`;

-- -----------------------------------------------------------------------------
-- 3. Truthful rows for three LinksPage features seed 018 registered but never
--    gave any plan a value. Without these, the registry says "off for every
--    plan" (the safe-floor default), which does not match what the product
--    actually does today. Nothing in the LinksPage programme enforces these
--    three through the registry; the rows exist so the registry DESCRIBES
--    today's behaviour correctly for anyone reading it or switching the
--    pricing engine on.
--      linkspage.all_templates — every plan sees all system templates today.
--      linkspage.agegate       — every plan can use the age gate today.
--      linkspage.custom_domain — needs a verified custom domain, and Free
--                                allows 0 custom domains (maxCustomDomains).
-- -----------------------------------------------------------------------------

-- linkspage.all_templates: Free yes · Basic yes · Premium yes · Enterprise yes
INSERT INTO `tblTierFeatures` (`tierID`, `featureUID`, `valueBoolean`)
SELECT t.`tierID`, f.`featureUID`,
       CASE t.`tierID`
           WHEN 'free'       THEN 1
           WHEN 'basic'      THEN 1
           WHEN 'premium'    THEN 1
           WHEN 'enterprise' THEN 1
       END
FROM   `tblSubscriptionTiers` t
JOIN   `tblFeatures` f ON f.`featureSlug` = 'linkspage.all_templates'
WHERE  t.`tierID` IN ('free', 'basic', 'premium', 'enterprise')
ON DUPLICATE KEY UPDATE `tierFeatureUID` = `tblTierFeatures`.`tierFeatureUID`;

-- linkspage.agegate: Free yes · Basic yes · Premium yes · Enterprise yes
INSERT INTO `tblTierFeatures` (`tierID`, `featureUID`, `valueBoolean`)
SELECT t.`tierID`, f.`featureUID`,
       CASE t.`tierID`
           WHEN 'free'       THEN 1
           WHEN 'basic'      THEN 1
           WHEN 'premium'    THEN 1
           WHEN 'enterprise' THEN 1
       END
FROM   `tblSubscriptionTiers` t
JOIN   `tblFeatures` f ON f.`featureSlug` = 'linkspage.agegate'
WHERE  t.`tierID` IN ('free', 'basic', 'premium', 'enterprise')
ON DUPLICATE KEY UPDATE `tierFeatureUID` = `tblTierFeatures`.`tierFeatureUID`;

-- linkspage.custom_domain: Free no · Basic yes · Premium yes · Enterprise yes
INSERT INTO `tblTierFeatures` (`tierID`, `featureUID`, `valueBoolean`)
SELECT t.`tierID`, f.`featureUID`,
       CASE t.`tierID`
           WHEN 'free'       THEN 0
           WHEN 'basic'      THEN 1
           WHEN 'premium'    THEN 1
           WHEN 'enterprise' THEN 1
       END
FROM   `tblSubscriptionTiers` t
JOIN   `tblFeatures` f ON f.`featureSlug` = 'linkspage.custom_domain'
WHERE  t.`tierID` IN ('free', 'basic', 'premium', 'enterprise')
ON DUPLICATE KEY UPDATE `tierFeatureUID` = `tblTierFeatures`.`tierFeatureUID`;
